// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WishListServer.src.Data;

#nullable disable

namespace WishListServer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260401163253_AddLoginToCredentials")]
    partial class AddLoginToCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Credential", b =>
                {
                    b.Property<Guid>("CredId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LoginHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CredId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "LoginHash")
                        .IsUnique();

                    b.ToTable("Credential");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid");

                    b.HasKey("ImageId");

                    b.HasIndex("WishId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wish", b =>
                {
                    b.Property<Guid>("WishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("WishId");

                    b.HasIndex("WishlistId");

                    b.HasIndex("WishlistId", "IsReceived");

                    b.ToTable("Wishes");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShareToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("WishlistId");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Credential", b =>
                {
                    b.HasOne("WishListServer.src.Data.Models.Database.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("WishListServer.src.Data.Models.Database.Credential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Image", b =>
                {
                    b.HasOne("WishListServer.src.Data.Models.Database.Wish", "Wish")
                        .WithOne("Image")
                        .HasForeignKey("WishListServer.src.Data.Models.Database.Image", "WishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wish");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wish", b =>
                {
                    b.HasOne("WishListServer.src.Data.Models.Database.Wishlist", "Wishlist")
                        .WithMany("Wishes")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wishlist", b =>
                {
                    b.HasOne("WishListServer.src.Data.Models.Database.User", "User")
                        .WithOne("Wishlist")
                        .HasForeignKey("WishListServer.src.Data.Models.Database.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.User", b =>
                {
                    b.Navigation("Credential")
                        .IsRequired();

                    b.Navigation("Wishlist")
                        .IsRequired();
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wish", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wishlist", b =>
                {
                    b.Navigation("Wishes");
                });
#pragma warning restore 612, 618
        }
    }
}
