// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WishListServer.src.Data;

#nullable disable

namespace WishListServer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260216145657_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid");

                    b.HasKey("ImageId");

                    b.HasIndex("WishId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wish", b =>
                {
                    b.Property<Guid>("WishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WishId");

                    b.ToTable("Wishes");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Image", b =>
                {
                    b.HasOne("WishListServer.src.Data.Models.Database.Wish", "Wish")
                        .WithOne("Image")
                        .HasForeignKey("WishListServer.src.Data.Models.Database.Image", "WishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wish");
                });

            modelBuilder.Entity("WishListServer.src.Data.Models.Database.Wish", b =>
                {
                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
